steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/portfolio:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/portfolio:latest'
      - '.'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/portfolio:$SHORT_SHA'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/portfolio:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=.
      - --image=gcr.io/$PROJECT_ID/portfolio:$SHORT_SHA
      - --location=us-central1

  # Alternative: Use gcloud for Cloud Run deployment (simpler)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'portfolio'
      - '--image'
      - 'gcr.io/$PROJECT_ID/portfolio:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# Images to be pushed to the registry
images:
  - 'gcr.io/$PROJECT_ID/portfolio:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/portfolio:latest'

# Set timeout
timeout: '1800s'

# Optional: Add options
options:
  machineType: 'N1_HIGHCPU_8'